#!/bin/sh
# guile-dir-locals.sh --- a .dir-locals.el for Geiser, from what this project measures.
#
#   sh guile-dir-locals.sh            # print the proposed .dir-locals.el on stdout
#   sh guile-dir-locals.sh --verify   # load .dir-locals.el in emacs --batch and check
#                                     # its ports and load path against the shell's
#
# Run from the project root: the port is derived from the working directory,
# exactly as guile-repl-paths.sh derives it, so the REPL must be started from the
# same directory.
#
# It never writes .dir-locals.el. Merging with an existing file is a judgement,
# and the skill makes it; this only proposes and checks.
#
# What the generated file does, and why each part is evaluated at LOAD time:
#   - probes guile3, guile-3.0, guile, so one committed file works on FreeBSD,
#     Debian and Homebrew (8178314 is the shell form of pinning; a pinned
#     geiser-guile-binary is the Emacs form).
#   - sets geiser-guile-load-path from the module directories that
#     guile-project-detect.sh found, relative to the file, so no absolute path
#     is committed.
#   - derives the REPL and proxy ports with the same formula as the shell,
#     37000 + cksum(slug) mod 900, because the slug is the absolute path and a
#     literal port would be wrong in every other checkout and worktree.
#
# The cost: `eval' forms make Emacs ask before applying them on first visit
# (enable-local-eval defaults to `maybe'). That prompt is expected; headless, it
# looks like a hang.

set -u

HERE=$(cd "$(dirname "$0")" && pwd)
. "$HERE/guile-repl-paths.sh"
. "$HERE/guile-project-detect.sh"

emit() {
    dirs=''
    for d in $GUILE_PROJECT_MODULE_DIRS; do
        dirs="$dirs \"$d\""
    done
    dirs=${dirs# }
    cat <<EOF
;;; Directory Local Variables --- Geiser for $GUILE_PROJECT_NAME
;;; Generated by the guile plugin's emacs-setup skill. Everything is derived at
;;; load time, so this file is safe to commit: no binary name, port or absolute
;;; path is baked in. Connect with M-x guile-project-connect (or geiser-connect
;;; to guile-project-proxy-port) after the repl-server skill has started the REPL.

((nil
  . ((eval
      . (let* ((root (expand-file-name
                      (locate-dominating-file default-directory ".dir-locals.el")))
               (slug (replace-regexp-in-string "[/.]" "-" (directory-file-name root)))
               (sum (car (split-string
                          (shell-command-to-string
                           (format "printf '%%s' %s | cksum"
                                   (shell-quote-argument slug)))))))
          (setq-local guile-project-repl-port
                      (+ 37000 (% (string-to-number sum) 900)))
          (setq-local guile-project-proxy-port (1+ guile-project-repl-port))
          (setq-local geiser-guile-load-path
                      (mapcar (lambda (d) (directory-file-name (expand-file-name d root)))
                              '($dirs)))
          (let ((bin (seq-find #'executable-find '("guile3" "guile-3.0" "guile"))))
            (when bin (setq-local geiser-guile-binary bin)))
          (unless (fboundp 'guile-project-connect)
            (defun guile-project-connect ()
              "Connect Geiser to this project's logging proxy."
              (interactive)
              (geiser-connect 'guile "127.0.0.1" guile-project-proxy-port))))))))
EOF
}

verify() {
    [ -f .dir-locals.el ] || { echo "verify: no .dir-locals.el in $(pwd)" >&2; exit 1; }
    command -v emacs >/dev/null 2>&1 || { echo "verify: emacs not found" >&2; exit 1; }
    # -Q so the user's configuration can neither help nor hurt; the eval form is
    # accepted explicitly because batch mode cannot answer the safety prompt.
    got=$(emacs -Q --batch --eval '
      (progn
        (setq enable-local-variables :all enable-local-eval t)
        (with-temp-buffer
          (setq default-directory (file-name-as-directory (expand-file-name ".")))
          (hack-dir-local-variables-non-file-buffer)
          (princ (format "%s %s %s\n"
                         (bound-and-true-p guile-project-repl-port)
                         (bound-and-true-p guile-project-proxy-port)
                         (mapconcat (quote identity)
                                    (bound-and-true-p geiser-guile-load-path) ":")))))' 2>&1 | tail -1)
    set -- $got
    want_load=''
    for d in $GUILE_PROJECT_MODULE_DIRS; do
        case $d in .) p=$GUILE_PROJECT_ROOT ;; *) p=$GUILE_PROJECT_ROOT/$d ;; esac
        want_load="${want_load:+$want_load:}$p"
    done
    status=0
    check() { # label got want
        if [ "$2" = "$3" ]; then printf 'ok    %-10s %s\n' "$1" "$2"
        else printf 'FAIL  %-10s emacs=%s shell=%s\n' "$1" "$2" "$3"; status=1; fi
    }
    check repl  "${1:-unset}" "$GUILE_REPL_PORT"
    check proxy "${2:-unset}" "$GUILE_REPL_PROXY_PORT"
    check load  "${3:-}"      "$want_load"
    [ "$status" -eq 0 ] || echo "verify: Emacs and the shell disagree; do not connect until they agree." >&2
    exit "$status"
}

case ${1:-} in
    --verify) verify ;;
    '')       emit ;;
    *)        echo "usage: sh guile-dir-locals.sh [--verify]" >&2; exit 2 ;;
esac
